version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: giorgio-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: giorgio
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - giorgio-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: giorgio-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - giorgio-network

  minio:
    image: minio/minio:latest
    container_name: giorgio-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_DEFAULT_BUCKETS: giorgio-storage
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - giorgio-network



volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  qdrant_storage:
    driver: local
  minio_data:
    driver: local

networks:
  giorgio-network:
    driver: bridge
